CREATE TABLE MEM_INFO
(
MEM_NUM NUMBER PRIMARY KEY,
MEM_CLASS_CODE VARCHAR2(4),
MEM_NAME VARCHAR2(15) NOT NULL UNIQUE,
MEM_ID VARCHAR2(12) NOT NULL UNIQUE,
MEM_PWD VARCHAR2(12) NOT NULL,
MEM_EMAIL VARCHAR2(320) NOT NULL UNIQUE,
MEM_ADDRESS VARCHAR2(320) NOT NULL
);

CREATE TABLE NOV_CATEGORY(
CATEGORY_CODE VARCHAR2(5) PRIMARY KEY,
CATEGORY_NAME VARCHAR2(12)
);

CREATE TABLE AUTHOR_INFO
(
AUTHOR_NUM NUMBER PRIMARY KEY,
MEM_NUM NUMBER,
COMPET_NUM NUMBER,
AUTHOR_REG_YN CHAR(2),
JUNIOR_YN CHAR(2)
);

CREATE TABLE COMPET_INFO
(
COMPETE_NUM NUMBER,
COMPET_NAME VARCHAR2(20),
COMPET_DATE DATE,
COMPET_REQUIRE_DOC VARCHAR2(100),
COMPET_ACTIVE_OR_NOT CHAR(2),
COMPET_RECRUIT_NUM NUMBER,
COMPET_CONTENT VARCHAR2(400)
);